"""create user table

Revision ID: f6b0fc8f53dd
Revises: dfa0b4c62272
Create Date: 2026-03-20 22:43:07.950993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6b0fc8f53dd'
down_revision: Union[str, Sequence[str], None] = 'dfa0b4c62272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_point', sa.Integer(), nullable=False),
    sa.Column('user_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_pk'),
    sa.UniqueConstraint('user_email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
